(defun f (L e)
    (list e L)
)
(setq L '(1 2 3))
(setq e 4)
(write-line "((4 1) (4 2) (4 3))")
(write (mapcar #'(lambda (L) (f L e)) L))
(write-line "")
(write-line "*** - MAPCAR: A proper list must not end with 4")
(write (mapcar #'f L e))
(write-line "")