(defun f (L)
    (list L)
)
(write-line "((1) (2) (3))")
(write (mapcar #'f '(1 2 3)))
(write-line "")
(write-line "(1 2 3)")
(write (mapcan #'f '(1 2 3)))
(write-line "")
(write-line "(1 2 3)")
(write (apply #'nconc (mapcar #'f '(1 2 3))))