(defun f (tree)
    (cond
        ((null tree) 0)
        ((null (cdr tree)) 1)
        (t (+ 1 (apply #'+ (mapcar #'f (cdr tree)))))
    )
)
(write (f '(a (b nil (d)) (c (e) (f)))))
(write-line "")
(write (f '(a (b (x) (d)) (c (e) (f)))))
(write-line "")
(write (f '(a (b (x) nil) (c (e) (f)))))
(write-line "")
(write (f '(a (b) (c (e) (f)))))
(write-line "")